# Imagen oficial de Node.js como base
FROM node:14

# Directorio de trabajo
WORKDIR /app

# Copia el archivo package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto del código del frontend al contenedor
COPY . .

# Compila el proyecto React para producción
RUN npm run build

# Expone el puerto 3000 para el frontend
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npm", "start"]