version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5002:5000"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - trello-network
    env_file: 
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3002:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - trello-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trello-network
    env_file: 
      - .env

volumes:
  postgres_data:

networks:
  trello-network: