version: '3'
services:
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_ENV=development
    command: npm start
    depends_on:
      - server
    networks:
      - trello-network

  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npx nodemon src/app.js
    ports:
      - "5002:5000"
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - trello-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trello-network

volumes:
  postgres_data:

networks:
  trello-network: