# Imagen oficial de Node.js
FROM node:16

# Directorio de trabajo
WORKDIR /app

# Copia el archivo package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install express-session connect-pg-simple dotenv

# Copia el resto del código del backend al contenedor
COPY . .

# Expone el puerto 5000 para el backend
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["npm", "start"]