FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# Copy the rest of the backend code
COPY . .

# Expose the port your server will run on
EXPOSE 5000

# Start the Express server
CMD ["node", "src/app.js"]